import { chromium } from 'playwright';
import { serveRepo } from '../tools/screenshot.mjs';
import path from 'node:path';
const [q, out, step, clip, size] = process.argv.slice(2);
const [w, h] = (size || '1600x900').split('x').map(Number);
const { origin, close } = await serveRepo(path.resolve('.'));
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: w, height: h } });
const errs = [];
p.on('console', m => m.type() === 'error' && errs.push(m.text()));
p.on('pageerror', e => errs.push(String(e)));
await p.goto(`${origin}/index.html${q}`, { waitUntil: 'load' });
await p.waitForFunction(() => window.__pkr?.isReady === true, null, { timeout: 15000 });
if (step && +step > 0) await p.evaluate(ms => window.__pkr.step(+ms), step);
await p.waitForTimeout(400);
const [x, y, cw, ch] = clip.split(',').map(Number);
await p.screenshot({ path: out, clip: { x, y, width: cw, height: ch } });
console.log('errs', errs.length, errs.slice(0, 3));
await b.close(); await close();
