import { serveRepo } from '../tools/screenshot.mjs';
import { chromium } from 'playwright';
const { origin, close } = await serveRepo();
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1600, height: 900 } });
const errs = [];
page.on('console', m => { if (m.type() === 'error') errs.push(m.text()); });
page.on('pageerror', e => errs.push('pageerror: ' + e.message));
await page.goto(`${origin}/index.html?screen=race&track=ryme-city&racer=pikachu&item=hyper-beam`, { waitUntil: 'load' });
await page.waitForFunction(() => window.__pkr?.isReady === true, null, { timeout: 20000 });
await page.evaluate(() => window.__pkr.seed(11));
await page.evaluate(() => window.__pkr.step(5000));
await page.waitForTimeout(300);
await page.screenshot({ path: 'gauntlet/shots/ri-r3-neon-5000.png' });
await page.keyboard.press('Space');
await page.evaluate(() => window.__pkr.step(200));
await page.waitForTimeout(200);
await page.screenshot({ path: 'gauntlet/shots/ri-r3-neon-beam.png' });
await page.screenshot({ path: 'gauntlet/shots/ri-r3-neon-beam-crop.png', clip: { x: 500, y: 250, width: 1000, height: 450 } });
console.log('ERRORS', errs.length, errs.slice(0, 4).join(' | '));
await browser.close(); await close();
