import { chromium } from 'playwright';
import { serveRepo } from '../tools/screenshot.mjs';
const { origin, close } = await serveRepo();
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 1600, height: 900 } });
const errs = [];
p.on('console', (m) => { if (m.type() === 'error') errs.push(m.text()); });
p.on('pageerror', (e) => errs.push(String(e)));
await p.goto(`${origin}/index.html?screen=race&item=hyper-beam`, { waitUntil: 'load' });
await p.waitForFunction(() => window.__pkr && window.__pkr.isReady, null, { timeout: 20000 });
const lanes = () => p.evaluate(() => window.__pkr.state().race.racers.map((r) => r.lane));
const a = await lanes();
await p.evaluate(() => { window.__pkr.press(' ', 60); });
await p.evaluate(() => window.__pkr.step(400));
const c2 = await lanes();
console.log('lanes before', a.join(','));
console.log('lanes after ', c2.join(','));
console.log('changed', a.filter((v, i) => Math.abs(v - c2[i]) > 0.05).length);
console.log(errs.length ? `ERRORS ${errs.slice(0,3).join(' | ')}` : 'no console errors');
await b.close(); await close();
