import { chromium } from 'playwright';
import { serveRepo } from '../tools/screenshot.mjs';
const { origin, close } = await serveRepo();
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 1600, height: 900 } });
const errs = [];
p.on('console', (m) => { if (m.type() === 'error') errs.push(m.text()); });
p.on('pageerror', (e) => errs.push(String(e)));
await p.goto(`${origin}/index.html?screen=race&item=hyper-beam`, { waitUntil: 'load' });
await p.waitForFunction(() => window.__pkr && window.__pkr.isReady, null, { timeout: 20000 });
const dump = () => p.evaluate(() => window.__pkr.state().race.racers.map((r) => Math.round(r.speed)));
await p.screenshot({ path: 'gauntlet/shots/ri-critic-before.png' });
const before = await dump();
await p.evaluate(() => { window.__pkr.press(' ', 60); });
await p.evaluate(() => window.__pkr.step(400));
await p.screenshot({ path: 'gauntlet/shots/ri-critic-after.png' });
const after = await dump();
console.log('before', before.join(','));
console.log('after ', after.join(','));
console.log('phase', await p.evaluate(() => window.__pkr.state().race.phase), 'item', await p.evaluate(() => window.__pkr.state().race.hud.item));
console.log(errs.length ? `ERRORS ${errs.slice(0,3).join(' | ')}` : 'no console errors');
await b.close(); await close();
