import { chromium } from 'playwright';
import { serveRepo } from '../tools/screenshot.mjs';
const q = process.argv[2] || '?screen=race&rolling=1';
const stepMs = Number(process.argv[3] || 1200);
const { origin, close } = await serveRepo();
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1600, height: 900 } });
page.on('console', (m) => { if (m.type() === 'error') console.log('ERR', m.text()); });
page.on('pageerror', (e) => console.log('PAGEERR', String(e)));
console.log('goto');
await page.goto(`${origin}/index.html${q}`, { waitUntil: 'load', timeout: 20000 });
console.log('wait ready');
await page.waitForFunction(() => window.__pkr && window.__pkr.isReady, null, { timeout: 15000 });
console.log('ready');
await page.evaluate((m) => window.__pkr.step(m), stepMs);
console.log('stepped');
const s = await page.evaluate(() => window.__pkr.state());
console.log('hud', JSON.stringify(s.race.hud), 'phase', s.race.phase);
await browser.close();
await close();
console.log('done');
