import { serveRepo } from './../tools/screenshot.mjs';
import { chromium } from 'playwright';
const { origin, server } = await serveRepo();
const b = await chromium.launch(); const p = await b.newPage({viewport:{width:1600,height:900}});
const errs=[]; p.on('console',m=>{if(m.type()==='error')errs.push(m.text())}); p.on('pageerror',e=>errs.push(''+e));
await p.goto(origin+'/index.html?screen=race&track=pallet-town&racer=pikachu');
await p.waitForFunction('window.__pkr && window.__pkr.isReady');
await p.evaluate(()=>window.__pkr.seed(7));
await p.evaluate(()=>window.__pkr.step(4000));
console.log('raceKeys',await p.evaluate(()=>JSON.stringify(Object.keys(window.__pkr.state().race))));
console.log('r0',await p.evaluate(()=>JSON.stringify(window.__pkr.state().race.racers[0])));
const f=async(t)=>{await p.evaluate(x=>window.__pkr.step(x),t);return p.evaluate(()=>{const r=window.__pkr.state().race.racers;return{n:r.length,ids:new Set(r.map(x=>x.id)).size,pos:r.map(x=>x.pos??x.place??x.position).sort((a,b)=>a-b).join(',')}})};
console.log('t30k',JSON.stringify(await f(26000)));
console.log('ERRS',errs.length);
await b.close(); server.close();
